spring:
  config:
    import:
      - classpath:jwt.yml
      - classpath:database.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  file:
    name: logs/application.log
  level:
    org:
      hibernate:
        sql: debug
    root: info